name: domain
description: A starting point for Dart libraries or applications.
version: 0.1.0

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies: {}

dev_dependencies:
  common_dev:
    path: ../common_dev
