apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stammgaeste
  name: rdb-config
data:
  TELEGRAM_CHAT_ID: "{{ .Values.telegram.chatId }}"
  SCHEDULE_ATTENDANCE_HOUR: "{{ .Values.schedule.attendancePollHour }}"
